routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\PostController;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', function () {
    return view('welcome.welcome');
});


Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::prefix('users')->name('users.')->middleware('auth')->group(function () {
    Route::controller(UserController::class)->group(function () {
        Route::get('/', 'index')->name('index')->middleware(['check_permission: user-show']);
        Route::get('/create', 'create')->name('create')->middleware(['check_permission:user-create']);
        Route::post('/', 'store')->name('store')->middleware(['check_permission:user-create']);
        Route::get('/{id}', 'show')->name('show')->middleware(['check_permission:user-show']);
        Route::get('{id}/edit', 'edit')->name('edit')->middleware(['check_permission:user-update']);
        Route::put('/{id}/update', 'update')->name('update')->middleware(['check_permission:user-update']);
        Route::delete('/{id}', 'destroy')->name('destroy')->middleware(['check_permission:user-delete']);
    });
});
Route::prefix('roles')->name('roles.')->middleware('auth')->group(function () {
    Route::controller(RoleController::class)->group(function () {
        Route::get('/', 'index')->name('index')->middleware(['check_permission:role-show']);
        Route::get('/create', 'create')->name('create')->middleware(['check_permission:role-create']);
        Route::post('/', 'store')->name('store')->middleware(['check_permission:role-create']);
        Route::get('/{id}', 'show')->name('show')->middleware(['check_permission:role-show']);
        Route::get('/{id}/edit', 'edit')->name('edit')->middleware(['check_permission:role-update']);
        Route::put('/{id}/update', 'update')->name('update')->middleware(['check_permission:role-update']);
        Route::delete('/{id}/destroy', 'destroy')->name('destroy')->middleware(['check_permission:role-delete']);
    });
});
Route::prefix('permissions')->name('permissions.')->middleware('auth')->group(function () {
    Route::controller(PermissionController::class)->group(function () {
        Route::get('/', 'index')->name('index')->middleware(['check_permission:permission-show']);
        Route::get('/create', 'create')->name('create')->middleware(['check_permission: permission-create']);
        Route::post('/', 'store')->name('store')->middleware(['check_permission: permission-create']);
        Route::get('/{id}', 'show')->name('show')->middleware(['check_permission: permission-show']);
        Route::get('/{id}/edit', 'edit')->name('edit')->middleware(['check_permission: permission-update']);
        Route::put('/{id}/update', 'update')->name('update')->middleware(['check_permission: permission-update']);
        Route::delete('/{id}', 'destroy')->name('destroy')->middleware(['check_permission: permission-delete']);
    });
});
Route::prefix('posts')->name('posts.')->middleware('auth')->group(function () {
    Route::controller(PostController::class)->group(function () {
        Route::get('/', 'index')->name('index')->middleware(['check_permission: post-show']);
        Route::get('/create', 'create')->name('create')->middleware(['check_permission: post-create']);
        Route::post('/', 'store')->name('store')->middleware(['check_permission: post-create']);
        Route::get('/{id}', 'show')->name('show')->middleware(['check_permission: post-show']);
        Route::get('/{id}/edit', 'edit')->name('edit')->middleware(['check_permission: post-update']);
        Route::put('/{id}/update', 'update')->name('update')->middleware(['check_permission: post-update']);
        Route::delete('/{id}', 'destroy')->name('destroy')->middleware(['check_permission: post-delete']);
    });
});

resources/views/permissions/layouts/side_navigation/sidebar_background.blade.php
<div>
                    <h6 class="mb-0">Sidebar Colors</h6>
                </div>
                <a href="javascript:void(0)" class="switch-trigger background-color">
                    <div class="badge-colors my-2 text-start">
                        <span class="badge filter bg-gradient-primary active" data-color="primary" onclick="sidebarColor(this)"></span>
                        <span class="badge filter bg-gradient-dark" data-color="dark" onclick="sidebarColor(this)"></span>
                        <span class="badge filter bg-gradient-info" data-color="info" onclick="sidebarColor(this)"></span>
                        <span class="badge filter bg-gradient-success" data-color="success" onclick="sidebarColor(this)"></span>
                        <span class="badge filter bg-gradient-warning" data-color="warning" onclick="sidebarColor(this)"></span>
                        <span class="badge filter bg-gradient-danger" data-color="danger" onclick="sidebarColor(this)"></span>
                    </div>
                </a>

resources/views/permissions/layouts/side_navigation/sidenav.blade.php
<aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3   bg-gradient-dark" id="sidenav-main">
        <hr class="horizontal light mt-0 mb-2">
        <div class="collapse navbar-collapse  w-auto  max-height-vh-100" id="sidenav-collapse-main">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link text-white" href="{{('home')}}">
                        <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="material-icons opacity-10">dashboard</i>
                        </div>
                        <span class="nav-link-text ms-1">Dashboard</span>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link text-white " href="{{ route('posts.index') }}">
                        <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="material-icons opacity-10">receipt_long</i>
                        </div>
                        <span class="nav-link-text ms-1">Posts</span>
                    </a>
                </li>
                <li class="nav-item mt-3">
                    <h6 class="ps-4 ms-2 text-uppercase text-xs text-white font-weight-bolder opacity-8">Account pages</h6>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white " href="{{ route('roles.index') }}">
                        <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="material-icons opacity-10">assignment_ind</i>
                        </div>
                        <span class="nav-link-text ms-1">Roles</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{{ route('users.index') }}">
                        <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="material-icons opacity-10">person_add</i>
                        </div>
                        <span class="nav-link-text ms-1">Users</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white active bg-gradient-primary" href="{{ route('permissions.index') }}">
                        <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="material-icons opacity-10">verified_user</i>
                        </div>
                        <span class="nav-link-text ms-1">Permission</span>
                    </a>
                </li>
            </ul>
        </div>
    </aside>

resources/views/permissions/layouts/side_navigation/sidenav_type.blade.php
<div class="mt-3">
    <h6 class="mb-0">Sidenav Type</h6>
    <p class="text-sm">Choose between 2 different sidenav types.</p>
</div>
<div class="d-flex">
    <button class="btn bg-gradient-dark px-3 mb-2 active" data-class="bg-gradient-dark" onclick="sidebarType(this)">Dark</button>
    <button class="btn bg-gradient-dark px-3 mb-2 ms-2" data-class="bg-transparent" onclick="sidebarType(this)">Transparent</button>
    <button class="btn bg-gradient-dark px-3 mb-2 ms-2" data-class="bg-white" onclick="sidebarType(this)">White</button>
</div>
<p class="text-sm d-xl-none d-block mt-2">You can change the sidenav type just on desktop view.</p>